name: Metrics

on:
  # 每天定时运行
  schedule:
    - cron: "0 0 * * *"
  # 手动触发
  workflow_dispatch:
  # 推送到主分支时触发
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # Metrics
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      # WakaTime Metrics       
      - name: Waka Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
